name: jest-and-docker-frontend

on: 
  pull_request:

jobs:
  has-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.check-changes.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current branch name
        id: get_branch_name
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
      - name: Check for changes in frontend directory
        id: check-changes
        uses: dorny/paths-filter@v3
        with:
          base:  ${{ github.ref }}
          filters: |
            frontend:
              - 'frontend/**'
      - name: Inspect has-changes output
        run: |
          echo "has-changes: ${{ steps.check-changes.outputs.frontend }}"
  
  test-front:
    needs: has-changes
    runs-on: ubuntu-latest
    if: needs.has-changes.outputs.has-changes == 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto frontend and run tests
        run: cd frontend && npm i && npm test

  docker:
    needs: [test-front, has-changes]
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'dev' && needs.has-changes.outputs.has-changes == 'true' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ secrets.DOCKERHUB_REPO_FRONTEND }}:latest, ${{ secrets.DOCKERHUB_REPO_FRONTEND }}:${{ github.sha }}

